In [15]:

import sys

import polars as pl
import pyarrow as pa

sys.path.insert(0, "..")

from services.analytics.analytics import recommend
from tests import datagen

In [2]:
df = pl.scan_ipc("../tests/data/large_dataset.arrow")
df

In [16]:
df = datagen.describe_mixed()
df

shape: (1_000, 36)
┌──────┬──────┬─────────┬───────────────┬───┬──────────────┬──────────────┬─────────────┬──────────┐
│ i8   ┆ i16  ┆ i32     ┆ i64           ┆ … ┆ list_str     ┆ arr_i32      ┆ struct      ┆ all_null │
│ ---  ┆ ---  ┆ ---     ┆ ---           ┆   ┆ ---          ┆ ---          ┆ ---         ┆ ---      │
│ i8   ┆ i16  ┆ i32     ┆ i64           ┆   ┆ list[str]    ┆ array[i32,   ┆ struct[2]   ┆ str      │
│      ┆      ┆         ┆               ┆   ┆              ┆ 3]           ┆             ┆          │
╞══════╪══════╪═════════╪═══════════════╪═══╪══════════════╪══════════════╪═════════════╪══════════╡
│ -87  ┆ -822 ┆ -822000 ┆ -822000000000 ┆ … ┆ null         ┆ [6, 5, 4]    ┆ {0,"alpha"} ┆ null     │
│      ┆      ┆         ┆ 000           ┆   ┆              ┆              ┆             ┆          │
│ -125 ┆ 547  ┆ 547000  ┆ 5470000000000 ┆ … ┆ ["3", "8",   ┆ [4, 9, 3]    ┆ null        ┆ null     │
│      ┆      ┆         ┆ 00            ┆   ┆ "6"]         ┆              ┆             ┆          │
│ -36  ┆ 309  ┆ 309000  ┆ null          ┆ … ┆ ["18", "14"] ┆ [8, 8, 9]    ┆ {1,"beta"}  ┆ null     │
│ 33   ┆ -123 ┆ -123000 ┆ -123000000000 ┆ … ┆ ["5", "18",  ┆ null         ┆ {1,"alpha"} ┆ null     │
│      ┆      ┆         ┆ 000           ┆   ┆ "8"]         ┆              ┆             ┆          │
│ null ┆ -134 ┆ -134000 ┆ -134000000000 ┆ … ┆ ["13", "13"] ┆ [7, 1, 0]    ┆ {2,"alpha"} ┆ null     │
│      ┆      ┆         ┆ 000           ┆   ┆              ┆              ┆             ┆          │
│ …    ┆ …    ┆ …       ┆ …             ┆ … ┆ …            ┆ …            ┆ …           ┆ …        │
│ 26   ┆ 252  ┆ 252000  ┆ 2520000000000 ┆ … ┆ ["12", "4",  ┆ [9, 7, 9]    ┆ {1,"beta"}  ┆ null     │
│      ┆      ┆         ┆ 00            ┆   ┆ "6"]         ┆              ┆             ┆          │
│ 47   ┆ 52   ┆ 52000   ┆ null          ┆ … ┆ ["16"]       ┆ [2, 7, 6]    ┆ {1,"beta"}  ┆ null     │
│ 66   ┆ -279 ┆ -279000 ┆ -279000000000 ┆ … ┆ ["14"]       ┆ [8, 2, 0]    ┆ {1,"alpha"} ┆ null     │
│      ┆      ┆         ┆ 000           ┆   ┆              ┆              ┆             ┆          │
│ 60   ┆ 923  ┆ 923000  ┆ 9230000000000 ┆ … ┆ ["1", "12"]  ┆ [3, 5, 5]    ┆ {0,"beta"}  ┆ null     │
│      ┆      ┆         ┆ 00            ┆   ┆              ┆              ┆             ┆          │
│ 16   ┆ 25   ┆ 25000   ┆ 2500000000000 ┆ … ┆ ["14", "10", ┆ [8, 6, 8]    ┆ {0,"beta"}  ┆ null     │
│      ┆      ┆         ┆ 0             ┆   ┆ "6"]         ┆              ┆             ┆          │
└──────┴──────┴─────────┴───────────────┴───┴──────────────┴──────────────┴─────────────┴──────────┘

In [19]:
recommender = recommend.RecommendRust(population_rows={"large_arrow":10000})
recommender.add({"large_arrow": df})

In [20]:
results = recommender.result()
results

shape: (36, 126)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ df_a       ┆ col_a    ┆ status   ┆ dtype     ┆ … ┆ inner_est ┆ inner_est ┆ inner_est ┆ inner_cla │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ _low      ┆ _high     ┆ imates_ag ┆ ss        │
│ str        ┆ str      ┆ enum     ┆ str       ┆   ┆ ---       ┆ ---       ┆ ree       ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ enum      │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆ bool      ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ large_arro ┆ i8       ┆ computed ┆ Int8      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ i16      ┆ computed ┆ Int16     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ i32      ┆ computed ┆ Int32     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ i64      ┆ computed ┆ Int64     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ i128     ┆ computed ┆ Int128    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ large_arro ┆ list_i64 ┆ computed ┆ List(Int6 ┆ … ┆ null      ┆ null      ┆ true      ┆ ordinal   │
│ w          ┆          ┆          ┆ 4)        ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ list_str ┆ computed ┆ List(Stri ┆ … ┆ null      ┆ null      ┆ true      ┆ ordinal   │
│ w          ┆          ┆          ┆ ng)       ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ arr_i32  ┆ computed ┆ Array(Int ┆ … ┆ null      ┆ null      ┆ true      ┆ ordinal   │
│ w          ┆          ┆          ┆ 32, shape ┆   ┆           ┆           ┆           ┆           │
│            ┆          ┆          ┆ =(3,))    ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ struct   ┆ computed ┆ Struct({' ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆ a':       ┆   ┆           ┆           ┆           ┆           │
│            ┆          ┆          ┆ Int64,    ┆   ┆           ┆           ┆           ┆           │
│            ┆          ┆          ┆ 'b':      ┆   ┆           ┆           ┆           ┆           │
│            ┆          ┆          ┆ Strin…    ┆   ┆           ┆           ┆           ┆           │
│ large_arro ┆ all_null ┆ computed ┆ String    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ w          ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘